(Feature) Support for multiple gpu testing
luxonis/luxonis-train pull request #42
Opened 2024-06-19 17:27 UTC by MatejRojec

- Modify the backbone models to support multi-GPU training using the DDP (Distributed Data Parallel) strategy.
- Resolve the `ddp_find_unused_parameters_true` error, which occurs when some backbone components are not utilized in the forward pass.

2024-06-20 03:13 UTC, kozlov721 approved these changes
LGTM

2024-06-20 11:35 UTC, tersekmatija requested changes

2024-06-20 11:35 UTC, tersekmatija commented on luxonis_train/nodes/efficientnet.py
> +        x = self.backbone.global_pool(x)
Is there a reason we append flattened features here instead of before global pool?
It seems also we have a list of size 5?

2024-06-20 11:35 UTC, tersekmatija commented on luxonis_train/nodes/efficientnet.py
> +        x = self.backbone.global_pool(x)
Whereas elsewhere it's a list of size 4?

2024-06-20 16:54 UTC, tersekmatija commented on luxonis_train/nodes/efficientnet.py
> +        x = self.backbone.global_pool(x)
I think maybe we check the paper if they define "blocks" to find out which features we should take?

2024-06-24 11:12 UTC, tersekmatija commented
@kozlov721 Do we require anywhere downstream that backbone outputs exactly 4 feature maps?

2024-07-09 16:04 UTC, kozlov721 commented
> @kozlov721 Do we require anywhere downstream that backbone outputs exactly 4 feature maps?

No, I don't think so

2024-07-09 16:17 UTC, tersekmatija commented
How would neck accept this then, the last 3 feature maps for example? @kozlov721

2024-07-09 17:33 UTC, kozlov721 commented
> How would neck accept this then, the last 3 feature maps for example? @kozlov721

The `RepPANNeck` needs at least as many feature maps as the value of `num_heads` parameter (3 by default). Then it uses the feature maps from the last one in the list.

2024-07-10 06:49 UTC, tersekmatija approved these changes

2024-07-10 06:49 UTC, tersekmatija commented
Okay, I think we can merge this then.

2024-07-11 13:43 UTC, merged